# Default initial positions for k1's ros2_control fake system

initial_positions:
  head_joint: 0
  left_ankle_joint: 0
  left_calf_joint: 0
  left_hip_joint: 0
  left_knee_joint: 0
  left_lower_arm_joint: 0
  left_shoulder_joint: 0
  left_thigh_joint: 0
  left_upper_arm_joint: 0
  right_ankle_joint: 0
  right_calf_joint: 0
  right_hip_joint: 0
  right_knee_joint: 0
  right_lower_arm_joint: 0
  right_shoulder_joint: 0
  right_thigh_joint: 0
  right_upper_arm_joint: 0