# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true

moveit_manage_controllers: false
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - k1_robot_controller

  k1_robot_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_hip
      - left_thigh
      - left_knee
      - left_calf
      - left_ankle
      - left_shoulder
      - left_arm_upper
      - left_arm_lower
      - right_hip
      - right_thigh
      - right_knee
      - right_calf
      - right_ankle
      - right_shoulder
      - right_upper
      - right_arm_lower
      - head
