# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    k1_right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    k1_left_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    k1_right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    k1_left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    k1_robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    k1_head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

k1_right_leg_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - right_hip_joint
      - right_thigh_joint
      - right_knee_joint
      - right_calf_joint
      - right_ankle_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
k1_left_leg_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - left_hip_joint
      - left_thigh_joint
      - left_knee_joint
      - left_calf_joint
      - left_ankle_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
k1_right_arm_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - right_shoulder_joint
      - right_upper_arm_joint
      - right_lower_arm_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
k1_left_arm_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - left_shoulder_joint
      - left_upper_arm_joint
      - left_lower_arm_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
k1_robot_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - left_hip_joint
      - left_thigh_joint
      - left_knee_joint
      - left_calf_joint
      - left_ankle_joint
      - left_shoulder_joint
      - left_upper_arm_joint
      - left_lower_arm_joint
      - right_hip_joint
      - right_thigh_joint
      - right_knee_joint
      - right_calf_joint
      - right_ankle_joint
      - right_shoulder_joint
      - right_upper_arm_joint
      - right_lower_arm_joint
      - head_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
k1_head_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - head
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
