# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    k1_right_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    k1_left_leg_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    k1_right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    k1_left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    k1_robot_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    k1_head_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

k1_right_leg_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - right_hip
      - right_thigh
      - right_knee
      - right_calf
      - right_ankle
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
k1_left_leg_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - left_hip
      - left_thigh
      - left_knee
      - left_calf
      - left_ankle
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
k1_right_arm_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - right_shoulder
      - right_upper
      - right_arm_lower
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
k1_left_arm_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - left_shoulder
      - left_arm_upper
      - left_arm_lower
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
k1_robot_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - left_hip
      - left_thigh
      - left_knee
      - left_calf
      - left_ankle
      - left_shoulder
      - left_arm_upper
      - left_arm_lower
      - right_hip
      - right_thigh
      - right_knee
      - right_calf
      - right_ankle
      - right_shoulder
      - right_upper
      - right_arm_lower
      - head
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
k1_head_controller:
  ros__parameters:
    open_loop_control: true
    allow_partial_joints_goal: true
    joints:
      - head
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
